"""Update relationships and foreign keys

Revision ID: 4a5d6420524e
Revises: 2c5da587ef5e
Create Date: 2024-07-30 23:50:10.723590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5d6420524e'
down_revision: Union[str, None] = '2c5da587ef5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boost', sa.Column('level_reward_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'boost', 'levelreward', ['level_reward_id'], ['id'])
    op.drop_constraint('levelreward_boost_id_fkey', 'levelreward', type_='foreignkey')
    op.drop_constraint('levelreward_prize_id_fkey', 'levelreward', type_='foreignkey')
    op.drop_column('levelreward', 'prize_id')
    op.drop_column('levelreward', 'boost_id')
    op.add_column('prize', sa.Column('level_reward_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'prize', 'levelreward', ['level_reward_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prize', type_='foreignkey')
    op.drop_column('prize', 'level_reward_id')
    op.add_column('levelreward', sa.Column('boost_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('levelreward', sa.Column('prize_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('levelreward_prize_id_fkey', 'levelreward', 'prize', ['prize_id'], ['id'])
    op.create_foreign_key('levelreward_boost_id_fkey', 'levelreward', 'boost', ['boost_id'], ['id'])
    op.drop_constraint(None, 'boost', type_='foreignkey')
    op.drop_column('boost', 'level_reward_id')
    # ### end Alembic commands ###
