"""initial migration

Revision ID: 2c5da587ef5e
Revises: 
Create Date: 2024-07-30 21:32:23.779969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5da587ef5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boost',
    sa.Column('type', sa.Enum('type', name='boosttype'), nullable=False),
    sa.Column('duration', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boost_id'), 'boost', ['id'], unique=False)
    op.create_table('level',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_level_id'), 'level', ['id'], unique=False)
    op.create_table('playerpoint',
    sa.Column('last_entry_date', sa.DateTime(), nullable=False),
    sa.Column('point_id', sa.Uuid(), nullable=False),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playerpoint_id'), 'playerpoint', ['id'], unique=False)
    op.create_table('point',
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('days', sa.Enum('one', name='days'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_id'), 'point', ['id'], unique=False)
    op.create_table('prize',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prize_id'), 'prize', ['id'], unique=False)
    op.create_table('levelreward',
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('prize_id', sa.UUID(), nullable=False),
    sa.Column('boost_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['boost_id'], ['boost.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.ForeignKeyConstraint(['prize_id'], ['prize.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_levelreward_id'), 'levelreward', ['id'], unique=False)
    op.create_index(op.f('ix_levelreward_level_id'), 'levelreward', ['level_id'], unique=False)
    op.create_table('player',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('player_point_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['player_point_id'], ['playerpoint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_id'), 'player', ['id'], unique=False)
    op.create_table('playerlevel',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('level_reward_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['level_reward_id'], ['levelreward.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playerlevel_id'), 'playerlevel', ['id'], unique=False)
    op.create_index(op.f('ix_playerlevel_player_id'), 'playerlevel', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playerlevel_player_id'), table_name='playerlevel')
    op.drop_index(op.f('ix_playerlevel_id'), table_name='playerlevel')
    op.drop_table('playerlevel')
    op.drop_index(op.f('ix_player_id'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_levelreward_level_id'), table_name='levelreward')
    op.drop_index(op.f('ix_levelreward_id'), table_name='levelreward')
    op.drop_table('levelreward')
    op.drop_index(op.f('ix_prize_id'), table_name='prize')
    op.drop_table('prize')
    op.drop_index(op.f('ix_point_id'), table_name='point')
    op.drop_table('point')
    op.drop_index(op.f('ix_playerpoint_id'), table_name='playerpoint')
    op.drop_table('playerpoint')
    op.drop_index(op.f('ix_level_id'), table_name='level')
    op.drop_table('level')
    op.drop_index(op.f('ix_boost_id'), table_name='boost')
    op.drop_table('boost')
    # ### end Alembic commands ###
